 return {
    "Did you know Crazyblox once hate his own poop because he thought it was chocolate?",
    "Did you know familiar ruins is based off of dark sci facility?",
    "Did you know beneath the ruins is based off of sATOMI SPRINGS?",
    "can i get uhhhhhhhhhhh",
    "waltuh",
    "Did you know that there is a 50% chance to see john cena at the end of castle tides?",
    "help",
    "Did you know that avm stands for anger volcanic management?",
    "i forgot im playing with my feet rn 😞",
    "me irl 🐵",
    "did you know ",
    "fallen is the best map (classic is even better)",
    "Did you know that Axiom used to be the hardest map? Crazy right?",
    "im not funny",
    "lol",
    "did you know FE2 stands for Flood Escape 2?",
    "did you know that fe2 was supossed to be called ESCAPE FROM GRANDMAS HOUSE 2?",
}
